# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-time']},
        ),
    ]
